version: '3.8'

services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - bbb-bot

  changeset-server:
    container_name: changeset-server
    build:
      context: https://github.com/bigbluebutton-bot/changeset-grpc.git
      dockerfile: Dockerfile
    networks:
      - bbb-bot


networks:
  bbb-bot:
    driver: bridge
