# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: [push]
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

#    - name: Build
#      run: go build -v ./...

    - name: API
      env: # an environment variable
        BBB_API_URL: ${{ secrets.BBB_API_URL }}
        BBB_API_SECRET: ${{ secrets.BBB_API_SECRET }}
        BBB_API_SHA: ${{ secrets.BBB_API_SHA }}
        BBB_CLIENT_URL: ${{ secrets.BBB_CLIENT_URL }}
        BBB_CLIENT_WS: ${{ secrets.BBB_CLIENT_WS }}
        BBB_PAD_URL: ${{ secrets.BBB_PAD_URL }}
        BBB_PAD_WS: ${{ secrets.BBB_PAD_WS }}
        BBB_WEBRTC_WS: ${{ secrets.BBB_WEBRTC_WS }}
        CHANGESET_EXTERNAL: ${{ secrets.CHANGESET_EXTERNAL }}
        CHANGESET_HOST: ${{ secrets.CHANGESET_HOST }}
        CHANGESET_PORT: ${{ secrets.CHANGESET_PORT }}
      run: cd api && go test -v ./...
