# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: [push]
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    env: # an environment variable
      BBB_URL: ${{ secrets.BBB_SERVER_URL }}
      BBB_SECRET: ${{ secrets.BBB_SERVER_SECRET }}

    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

#    - name: Build
#      run: go build -v ./...

    - name: Test
      run: go test -v ./...
